name: Node.js CI Pipeline


on:
  push:
    branches: ["main"]


jobs:

  build-and-test:

    runs-on: ubuntu-latest


    steps:

    # Download code
    - name: Checkout Code
      uses: actions/checkout@v4


    # Frontend install + test
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install


    - name: Run Frontend Tests
      run: |
        cd frontend
        npm test


    # Backend install + test
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install


    - name: Run Backend Tests
      run: |
        cd backend
        npm test


    # Docker test
    - name: Test Docker Build
      run: |
        docker compose build